sudo: required
services: 
  - docker

before_install:
  - docker build -t cjthoma1/react-test -f ./client/Dockerfile.dev ./client

script: 
  - docker run cjthoma1/react-test npm test -- --coverage

after_success: 
  - docker build -t cjthoma1/multi-client ./client
  - docker build -t cjthoma1/multi-nginx ./nginx
  - docker build -t cjthoma1/multi-server ./server
  - docker build -t cjthoma1/multi-worker ./worker
  # Log in to Docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push cjthoma1/multi-client
  - docker push cjthoma1/multi-nginx
  - docker push cjthoma1/multi-server
  - docker push cjthoma1/multi-worker